// Code generated by go-swagger; DO NOT EDIT.

package uploads_2020_11_01_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UploadDestination Information about an upload destination.
//
// swagger:model UploadDestination
type UploadDestination struct {

	// The headers to include in the upload request.
	Headers interface{} `json:"headers,omitempty"`

	// The unique identifier for the upload destination.
	UploadDestinationID string `json:"uploadDestinationId,omitempty"`

	// The URL for the upload destination.
	URL string `json:"url,omitempty"`
}

// Validate validates this upload destination
func (m *UploadDestination) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upload destination based on context it is used
func (m *UploadDestination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UploadDestination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadDestination) UnmarshalBinary(b []byte) error {
	var res UploadDestination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
