// Code generated by go-swagger; DO NOT EDIT.

package orders_v0_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FulfillmentInstruction Contains the instructions about the fulfillment like where should it be fulfilled from.
//
// swagger:model FulfillmentInstruction
type FulfillmentInstruction struct {

	// Denotes the recommended `sourceId` where the order should be fulfilled from.
	FulfillmentSupplySourceID string `json:"FulfillmentSupplySourceId,omitempty"`
}

// Validate validates this fulfillment instruction
func (m *FulfillmentInstruction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this fulfillment instruction based on context it is used
func (m *FulfillmentInstruction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FulfillmentInstruction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FulfillmentInstruction) UnmarshalBinary(b []byte) error {
	var res FulfillmentInstruction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
