// Code generated by go-swagger; DO NOT EDIT.

package fulfillment_outbound_2020_07_01_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeliveryMessage Localized messaging for a delivery offering.
//
// swagger:model DeliveryMessage
type DeliveryMessage struct {

	// The locale for the message (for example, en_US).
	Locale string `json:"locale,omitempty"`

	// The message content for a delivery offering.
	Text string `json:"text,omitempty"`
}

// Validate validates this delivery message
func (m *DeliveryMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delivery message based on context it is used
func (m *DeliveryMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeliveryMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeliveryMessage) UnmarshalBinary(b []byte) error {
	var res DeliveryMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
