// Code generated by go-swagger; DO NOT EDIT.

package orders_2026_01_01_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PackageItem Individual order item contained within a shipping package.
//
// swagger:model PackageItem
type PackageItem struct {

	// Unique identifier of the order item included in this package.
	// Required: true
	OrderItemID *string `json:"orderItemId"`

	// Number of units of this item included in the package shipment.
	// Required: true
	Quantity *int64 `json:"quantity"`

	// The transparency codes associated with this item for product authentication.
	TransparencyCodes []string `json:"transparencyCodes"`
}

// Validate validates this package item
func (m *PackageItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderItemID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PackageItem) validateOrderItemID(formats strfmt.Registry) error {

	if err := validate.Required("orderItemId", "body", m.OrderItemID); err != nil {
		return err
	}

	return nil
}

func (m *PackageItem) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this package item based on context it is used
func (m *PackageItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PackageItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PackageItem) UnmarshalBinary(b []byte) error {
	var res PackageItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
