// Code generated by go-swagger; DO NOT EDIT.

package transfers_2024_06_01_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentMethodDetails The details of a payment method.
//
// swagger:model PaymentMethodDetails
type PaymentMethodDetails struct {

	// The name of the account holder who is registered for the payment method.
	AccountHolderName string `json:"accountHolderName,omitempty"`

	// The payment method assignment type, whether it is assigned as default to the given marketplace or not.
	AssignmentType AssignmentType `json:"assignmentType,omitempty"`

	// The two-letter country code in ISO 3166-1 alpha-2 format. For payment methods in the `card` category, the code is for the country where the card was issued. For payment methods in the `bank account` category, the code is for the country where the account is located.
	// Example: US
	CountryCode string `json:"countryCode,omitempty"`

	// The expiration date of the card used for payment.
	ExpiryDate *ExpiryDate `json:"expiryDate,omitempty"`

	// The payment method identifier.
	// Example: 0h_TU_CUS_4058fe2a-da6b-4b82-8e48-b20ff2eb4f6d
	PaymentMethodID string `json:"paymentMethodId,omitempty"`

	// The payment method type.
	PaymentMethodType PaymentMethodType `json:"paymentMethodType,omitempty"`

	// The last three or four digits of the payment method.
	// Example: 321
	Tail string `json:"tail,omitempty"`
}

// Validate validates this payment method details
func (m *PaymentMethodDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssignmentType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpiryDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePaymentMethodType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PaymentMethodDetails) validateAssignmentType(formats strfmt.Registry) error {
	if swag.IsZero(m.AssignmentType) { // not required
		return nil
	}

	if err := m.AssignmentType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("assignmentType")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("assignmentType")
		}
		return err
	}

	return nil
}

func (m *PaymentMethodDetails) validateExpiryDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpiryDate) { // not required
		return nil
	}

	if m.ExpiryDate != nil {
		if err := m.ExpiryDate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("expiryDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("expiryDate")
			}
			return err
		}
	}

	return nil
}

func (m *PaymentMethodDetails) validatePaymentMethodType(formats strfmt.Registry) error {
	if swag.IsZero(m.PaymentMethodType) { // not required
		return nil
	}

	if err := m.PaymentMethodType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("paymentMethodType")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("paymentMethodType")
		}
		return err
	}

	return nil
}

// ContextValidate validate this payment method details based on the context it is used
func (m *PaymentMethodDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAssignmentType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExpiryDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePaymentMethodType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PaymentMethodDetails) contextValidateAssignmentType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.AssignmentType.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("assignmentType")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("assignmentType")
		}
		return err
	}

	return nil
}

func (m *PaymentMethodDetails) contextValidateExpiryDate(ctx context.Context, formats strfmt.Registry) error {

	if m.ExpiryDate != nil {
		if err := m.ExpiryDate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("expiryDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("expiryDate")
			}
			return err
		}
	}

	return nil
}

func (m *PaymentMethodDetails) contextValidatePaymentMethodType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.PaymentMethodType.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("paymentMethodType")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("paymentMethodType")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PaymentMethodDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentMethodDetails) UnmarshalBinary(b []byte) error {
	var res PaymentMethodDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
