// Code generated by go-swagger; DO NOT EDIT.

package promotions_2025_12_01_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VariableFee Performance based fee, usually represented as a percentage of promotion sales with a cap amount.
// Example: {"feeCapAmount":{"amount":1000,"currencyCode":"USD"},"salesPercentage":0.05}
//
// swagger:model VariableFee
type VariableFee struct {

	// fee cap amount
	FeeCapAmount *Currency `json:"feeCapAmount,omitempty"`

	// Sales Percentage
	// Example: 0.05
	// Required: true
	// Maximum: 1
	// Minimum: 0
	SalesPercentage *float64 `json:"salesPercentage"`
}

// Validate validates this variable fee
func (m *VariableFee) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFeeCapAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSalesPercentage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VariableFee) validateFeeCapAmount(formats strfmt.Registry) error {
	if swag.IsZero(m.FeeCapAmount) { // not required
		return nil
	}

	if m.FeeCapAmount != nil {
		if err := m.FeeCapAmount.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("feeCapAmount")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("feeCapAmount")
			}
			return err
		}
	}

	return nil
}

func (m *VariableFee) validateSalesPercentage(formats strfmt.Registry) error {

	if err := validate.Required("salesPercentage", "body", m.SalesPercentage); err != nil {
		return err
	}

	if err := validate.Minimum("salesPercentage", "body", *m.SalesPercentage, 0, false); err != nil {
		return err
	}

	if err := validate.Maximum("salesPercentage", "body", *m.SalesPercentage, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this variable fee based on the context it is used
func (m *VariableFee) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFeeCapAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VariableFee) contextValidateFeeCapAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.FeeCapAmount != nil {
		if err := m.FeeCapAmount.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("feeCapAmount")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("feeCapAmount")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VariableFee) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VariableFee) UnmarshalBinary(b []byte) error {
	var res VariableFee
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
