// Code generated by go-swagger; DO NOT EDIT.

package vendor_shipments_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContainerSequenceNumbers Container sequence numbers that are involved in this shipment.
//
// swagger:model ContainerSequenceNumbers
type ContainerSequenceNumbers struct {

	// A list of containers shipped
	ContainerSequenceNumber string `json:"containerSequenceNumber,omitempty"`
}

// Validate validates this container sequence numbers
func (m *ContainerSequenceNumbers) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this container sequence numbers based on context it is used
func (m *ContainerSequenceNumbers) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerSequenceNumbers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerSequenceNumbers) UnmarshalBinary(b []byte) error {
	var res ContainerSequenceNumbers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
