// Code generated by go-swagger; DO NOT EDIT.

package replenishment_2022_11_07_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// MarketplaceID The marketplace identifier. The supported marketplaces for both sellers and vendors are US, CA, ES, UK, FR, IT, IN, DE and JP. The supported marketplaces for vendors only are BR, AU, MX, AE and NL. Refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids) to find the identifier for the marketplace.
//
// swagger:model MarketplaceId
type MarketplaceID string

// Validate validates this marketplace Id
func (m MarketplaceID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this marketplace Id based on context it is used
func (m MarketplaceID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
