// Code generated by go-swagger; DO NOT EDIT.

package fba_outbound

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/renabled/amzn-sp-api-go/api/fulfillmentOutbound_2020-07-01/fulfillment_outbound_2020_07_01_models"
)

// DeliveryOfferingsReader is a Reader for the DeliveryOfferings structure.
type DeliveryOfferingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeliveryOfferingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeliveryOfferingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeliveryOfferingsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeliveryOfferingsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeliveryOfferingsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeliveryOfferingsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeliveryOfferingsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeliveryOfferingsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeliveryOfferingsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeliveryOfferingsOK creates a DeliveryOfferingsOK with default headers values
func NewDeliveryOfferingsOK() *DeliveryOfferingsOK {
	return &DeliveryOfferingsOK{}
}

/*
DeliveryOfferingsOK describes a response with status code 200, with default header values.

Success.
*/
type DeliveryOfferingsOK struct {

	/* Your rate limit (requests per second) for this operation.
	 */
	XAmznRateLimitLimit string

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse
}

// IsSuccess returns true when this delivery offerings o k response has a 2xx status code
func (o *DeliveryOfferingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delivery offerings o k response has a 3xx status code
func (o *DeliveryOfferingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delivery offerings o k response has a 4xx status code
func (o *DeliveryOfferingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delivery offerings o k response has a 5xx status code
func (o *DeliveryOfferingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delivery offerings o k response a status code equal to that given
func (o *DeliveryOfferingsOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeliveryOfferingsOK) Error() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsOK  %+v", 200, o.Payload)
}

func (o *DeliveryOfferingsOK) String() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsOK  %+v", 200, o.Payload)
}

func (o *DeliveryOfferingsOK) GetPayload() *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse {
	return o.Payload
}

func (o *DeliveryOfferingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RateLimit-Limit
	hdrXAmznRateLimitLimit := response.GetHeader("x-amzn-RateLimit-Limit")

	if hdrXAmznRateLimitLimit != "" {
		o.XAmznRateLimitLimit = hdrXAmznRateLimitLimit
	}

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeliveryOfferingsBadRequest creates a DeliveryOfferingsBadRequest with default headers values
func NewDeliveryOfferingsBadRequest() *DeliveryOfferingsBadRequest {
	return &DeliveryOfferingsBadRequest{}
}

/*
DeliveryOfferingsBadRequest describes a response with status code 400, with default header values.

Request has missing or invalid parameters and cannot be parsed.
*/
type DeliveryOfferingsBadRequest struct {

	/* Your rate limit (requests per second) for this operation.
	 */
	XAmznRateLimitLimit string

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse
}

// IsSuccess returns true when this delivery offerings bad request response has a 2xx status code
func (o *DeliveryOfferingsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delivery offerings bad request response has a 3xx status code
func (o *DeliveryOfferingsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delivery offerings bad request response has a 4xx status code
func (o *DeliveryOfferingsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delivery offerings bad request response has a 5xx status code
func (o *DeliveryOfferingsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delivery offerings bad request response a status code equal to that given
func (o *DeliveryOfferingsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DeliveryOfferingsBadRequest) Error() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsBadRequest  %+v", 400, o.Payload)
}

func (o *DeliveryOfferingsBadRequest) String() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsBadRequest  %+v", 400, o.Payload)
}

func (o *DeliveryOfferingsBadRequest) GetPayload() *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse {
	return o.Payload
}

func (o *DeliveryOfferingsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RateLimit-Limit
	hdrXAmznRateLimitLimit := response.GetHeader("x-amzn-RateLimit-Limit")

	if hdrXAmznRateLimitLimit != "" {
		o.XAmznRateLimitLimit = hdrXAmznRateLimitLimit
	}

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeliveryOfferingsUnauthorized creates a DeliveryOfferingsUnauthorized with default headers values
func NewDeliveryOfferingsUnauthorized() *DeliveryOfferingsUnauthorized {
	return &DeliveryOfferingsUnauthorized{}
}

/*
DeliveryOfferingsUnauthorized describes a response with status code 401, with default header values.

The request's Authorization header is not formatted correctly or does not contain a valid token.
*/
type DeliveryOfferingsUnauthorized struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse
}

// IsSuccess returns true when this delivery offerings unauthorized response has a 2xx status code
func (o *DeliveryOfferingsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delivery offerings unauthorized response has a 3xx status code
func (o *DeliveryOfferingsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delivery offerings unauthorized response has a 4xx status code
func (o *DeliveryOfferingsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delivery offerings unauthorized response has a 5xx status code
func (o *DeliveryOfferingsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delivery offerings unauthorized response a status code equal to that given
func (o *DeliveryOfferingsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *DeliveryOfferingsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsUnauthorized  %+v", 401, o.Payload)
}

func (o *DeliveryOfferingsUnauthorized) String() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsUnauthorized  %+v", 401, o.Payload)
}

func (o *DeliveryOfferingsUnauthorized) GetPayload() *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse {
	return o.Payload
}

func (o *DeliveryOfferingsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeliveryOfferingsForbidden creates a DeliveryOfferingsForbidden with default headers values
func NewDeliveryOfferingsForbidden() *DeliveryOfferingsForbidden {
	return &DeliveryOfferingsForbidden{}
}

/*
DeliveryOfferingsForbidden describes a response with status code 403, with default header values.

Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature.
*/
type DeliveryOfferingsForbidden struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse
}

// IsSuccess returns true when this delivery offerings forbidden response has a 2xx status code
func (o *DeliveryOfferingsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delivery offerings forbidden response has a 3xx status code
func (o *DeliveryOfferingsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delivery offerings forbidden response has a 4xx status code
func (o *DeliveryOfferingsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delivery offerings forbidden response has a 5xx status code
func (o *DeliveryOfferingsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delivery offerings forbidden response a status code equal to that given
func (o *DeliveryOfferingsForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *DeliveryOfferingsForbidden) Error() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsForbidden  %+v", 403, o.Payload)
}

func (o *DeliveryOfferingsForbidden) String() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsForbidden  %+v", 403, o.Payload)
}

func (o *DeliveryOfferingsForbidden) GetPayload() *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse {
	return o.Payload
}

func (o *DeliveryOfferingsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeliveryOfferingsNotFound creates a DeliveryOfferingsNotFound with default headers values
func NewDeliveryOfferingsNotFound() *DeliveryOfferingsNotFound {
	return &DeliveryOfferingsNotFound{}
}

/*
DeliveryOfferingsNotFound describes a response with status code 404, with default header values.

The specified resource does not exist.
*/
type DeliveryOfferingsNotFound struct {

	/* Your rate limit (requests per second) for this operation.
	 */
	XAmznRateLimitLimit string

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse
}

// IsSuccess returns true when this delivery offerings not found response has a 2xx status code
func (o *DeliveryOfferingsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delivery offerings not found response has a 3xx status code
func (o *DeliveryOfferingsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delivery offerings not found response has a 4xx status code
func (o *DeliveryOfferingsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delivery offerings not found response has a 5xx status code
func (o *DeliveryOfferingsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delivery offerings not found response a status code equal to that given
func (o *DeliveryOfferingsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeliveryOfferingsNotFound) Error() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsNotFound  %+v", 404, o.Payload)
}

func (o *DeliveryOfferingsNotFound) String() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsNotFound  %+v", 404, o.Payload)
}

func (o *DeliveryOfferingsNotFound) GetPayload() *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse {
	return o.Payload
}

func (o *DeliveryOfferingsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RateLimit-Limit
	hdrXAmznRateLimitLimit := response.GetHeader("x-amzn-RateLimit-Limit")

	if hdrXAmznRateLimitLimit != "" {
		o.XAmznRateLimitLimit = hdrXAmznRateLimitLimit
	}

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeliveryOfferingsTooManyRequests creates a DeliveryOfferingsTooManyRequests with default headers values
func NewDeliveryOfferingsTooManyRequests() *DeliveryOfferingsTooManyRequests {
	return &DeliveryOfferingsTooManyRequests{}
}

/*
DeliveryOfferingsTooManyRequests describes a response with status code 429, with default header values.

The frequency of requests was greater than allowed.
*/
type DeliveryOfferingsTooManyRequests struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse
}

// IsSuccess returns true when this delivery offerings too many requests response has a 2xx status code
func (o *DeliveryOfferingsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delivery offerings too many requests response has a 3xx status code
func (o *DeliveryOfferingsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delivery offerings too many requests response has a 4xx status code
func (o *DeliveryOfferingsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this delivery offerings too many requests response has a 5xx status code
func (o *DeliveryOfferingsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this delivery offerings too many requests response a status code equal to that given
func (o *DeliveryOfferingsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *DeliveryOfferingsTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsTooManyRequests  %+v", 429, o.Payload)
}

func (o *DeliveryOfferingsTooManyRequests) String() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsTooManyRequests  %+v", 429, o.Payload)
}

func (o *DeliveryOfferingsTooManyRequests) GetPayload() *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse {
	return o.Payload
}

func (o *DeliveryOfferingsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeliveryOfferingsInternalServerError creates a DeliveryOfferingsInternalServerError with default headers values
func NewDeliveryOfferingsInternalServerError() *DeliveryOfferingsInternalServerError {
	return &DeliveryOfferingsInternalServerError{}
}

/*
DeliveryOfferingsInternalServerError describes a response with status code 500, with default header values.

An unexpected condition occurred that prevented the server from fulfilling the request.
*/
type DeliveryOfferingsInternalServerError struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse
}

// IsSuccess returns true when this delivery offerings internal server error response has a 2xx status code
func (o *DeliveryOfferingsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delivery offerings internal server error response has a 3xx status code
func (o *DeliveryOfferingsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delivery offerings internal server error response has a 4xx status code
func (o *DeliveryOfferingsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delivery offerings internal server error response has a 5xx status code
func (o *DeliveryOfferingsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delivery offerings internal server error response a status code equal to that given
func (o *DeliveryOfferingsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *DeliveryOfferingsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsInternalServerError  %+v", 500, o.Payload)
}

func (o *DeliveryOfferingsInternalServerError) String() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsInternalServerError  %+v", 500, o.Payload)
}

func (o *DeliveryOfferingsInternalServerError) GetPayload() *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse {
	return o.Payload
}

func (o *DeliveryOfferingsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeliveryOfferingsServiceUnavailable creates a DeliveryOfferingsServiceUnavailable with default headers values
func NewDeliveryOfferingsServiceUnavailable() *DeliveryOfferingsServiceUnavailable {
	return &DeliveryOfferingsServiceUnavailable{}
}

/*
DeliveryOfferingsServiceUnavailable describes a response with status code 503, with default header values.

Temporary overloading or maintenance of the server.
*/
type DeliveryOfferingsServiceUnavailable struct {

	/* Unique request reference identifier.
	 */
	XAmznRequestID string

	Payload *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse
}

// IsSuccess returns true when this delivery offerings service unavailable response has a 2xx status code
func (o *DeliveryOfferingsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delivery offerings service unavailable response has a 3xx status code
func (o *DeliveryOfferingsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delivery offerings service unavailable response has a 4xx status code
func (o *DeliveryOfferingsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delivery offerings service unavailable response has a 5xx status code
func (o *DeliveryOfferingsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delivery offerings service unavailable response a status code equal to that given
func (o *DeliveryOfferingsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

func (o *DeliveryOfferingsServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeliveryOfferingsServiceUnavailable) String() string {
	return fmt.Sprintf("[POST /fba/outbound/2020-07-01/deliveryOfferings][%d] deliveryOfferingsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeliveryOfferingsServiceUnavailable) GetPayload() *fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse {
	return o.Payload
}

func (o *DeliveryOfferingsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-amzn-RequestId
	hdrXAmznRequestID := response.GetHeader("x-amzn-RequestId")

	if hdrXAmznRequestID != "" {
		o.XAmznRequestID = hdrXAmznRequestID
	}

	o.Payload = new(fulfillment_outbound_2020_07_01_models.GetDeliveryOfferingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
