// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/renabled/amzn-sp-api-go/api/shippingV2/shipping_v2_models"
)

// NewGetCollectionFormHistoryParams creates a new GetCollectionFormHistoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollectionFormHistoryParams() *GetCollectionFormHistoryParams {
	return &GetCollectionFormHistoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectionFormHistoryParamsWithTimeout creates a new GetCollectionFormHistoryParams object
// with the ability to set a timeout on a request.
func NewGetCollectionFormHistoryParamsWithTimeout(timeout time.Duration) *GetCollectionFormHistoryParams {
	return &GetCollectionFormHistoryParams{
		timeout: timeout,
	}
}

// NewGetCollectionFormHistoryParamsWithContext creates a new GetCollectionFormHistoryParams object
// with the ability to set a context for a request.
func NewGetCollectionFormHistoryParamsWithContext(ctx context.Context) *GetCollectionFormHistoryParams {
	return &GetCollectionFormHistoryParams{
		Context: ctx,
	}
}

// NewGetCollectionFormHistoryParamsWithHTTPClient creates a new GetCollectionFormHistoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollectionFormHistoryParamsWithHTTPClient(client *http.Client) *GetCollectionFormHistoryParams {
	return &GetCollectionFormHistoryParams{
		HTTPClient: client,
	}
}

/*
GetCollectionFormHistoryParams contains all the parameters to send to the API endpoint

	for the get collection form history operation.

	Typically these are written to a http.Request.
*/
type GetCollectionFormHistoryParams struct {

	// Body.
	Body *shipping_v2_models.GetCollectionFormHistoryRequest

	/* XAmznShippingBusinessID.

	   Amazon shipping business to assume for this request. The default is AmazonShipping_UK.
	*/
	XAmznShippingBusinessID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get collection form history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionFormHistoryParams) WithDefaults() *GetCollectionFormHistoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get collection form history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionFormHistoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get collection form history params
func (o *GetCollectionFormHistoryParams) WithTimeout(timeout time.Duration) *GetCollectionFormHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collection form history params
func (o *GetCollectionFormHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collection form history params
func (o *GetCollectionFormHistoryParams) WithContext(ctx context.Context) *GetCollectionFormHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collection form history params
func (o *GetCollectionFormHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collection form history params
func (o *GetCollectionFormHistoryParams) WithHTTPClient(client *http.Client) *GetCollectionFormHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collection form history params
func (o *GetCollectionFormHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get collection form history params
func (o *GetCollectionFormHistoryParams) WithBody(body *shipping_v2_models.GetCollectionFormHistoryRequest) *GetCollectionFormHistoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get collection form history params
func (o *GetCollectionFormHistoryParams) SetBody(body *shipping_v2_models.GetCollectionFormHistoryRequest) {
	o.Body = body
}

// WithXAmznShippingBusinessID adds the xAmznShippingBusinessID to the get collection form history params
func (o *GetCollectionFormHistoryParams) WithXAmznShippingBusinessID(xAmznShippingBusinessID *string) *GetCollectionFormHistoryParams {
	o.SetXAmznShippingBusinessID(xAmznShippingBusinessID)
	return o
}

// SetXAmznShippingBusinessID adds the xAmznShippingBusinessId to the get collection form history params
func (o *GetCollectionFormHistoryParams) SetXAmznShippingBusinessID(xAmznShippingBusinessID *string) {
	o.XAmznShippingBusinessID = xAmznShippingBusinessID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectionFormHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.XAmznShippingBusinessID != nil {

		// header param x-amzn-shipping-business-id
		if err := r.SetHeaderParam("x-amzn-shipping-business-id", *o.XAmznShippingBusinessID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
