// Code generated by go-swagger; DO NOT EDIT.

package external_fulfillment_shipments_2024_09_11_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ComplianceAttributes All necessary compliance attributes specific to the line item.
//
// swagger:model ComplianceAttributes
type ComplianceAttributes struct {

	// Whether the country of origin must be provided for this line item.
	// Required: true
	CountryOfOriginRequirement *RequirementLevel `json:"countryOfOriginRequirement"`

	// Whether hazardous material labels must be applied on packages containing this line item.
	// Required: true
	HazmatLabelsRequirement *RequirementLevel `json:"hazmatLabelsRequirement"`

	// Whether the item value must be provided for this line item.
	// Required: true
	ItemValueRequirement *RequirementLevel `json:"itemValueRequirement"`

	// Whether serial numbers must be provided for this line item.
	// Required: true
	SerialNumberRequirement *RequirementLevel `json:"serialNumberRequirement"`
}

// Validate validates this compliance attributes
func (m *ComplianceAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCountryOfOriginRequirement(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHazmatLabelsRequirement(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateItemValueRequirement(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSerialNumberRequirement(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComplianceAttributes) validateCountryOfOriginRequirement(formats strfmt.Registry) error {

	if err := validate.Required("countryOfOriginRequirement", "body", m.CountryOfOriginRequirement); err != nil {
		return err
	}

	if err := validate.Required("countryOfOriginRequirement", "body", m.CountryOfOriginRequirement); err != nil {
		return err
	}

	if m.CountryOfOriginRequirement != nil {
		if err := m.CountryOfOriginRequirement.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("countryOfOriginRequirement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("countryOfOriginRequirement")
			}
			return err
		}
	}

	return nil
}

func (m *ComplianceAttributes) validateHazmatLabelsRequirement(formats strfmt.Registry) error {

	if err := validate.Required("hazmatLabelsRequirement", "body", m.HazmatLabelsRequirement); err != nil {
		return err
	}

	if err := validate.Required("hazmatLabelsRequirement", "body", m.HazmatLabelsRequirement); err != nil {
		return err
	}

	if m.HazmatLabelsRequirement != nil {
		if err := m.HazmatLabelsRequirement.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("hazmatLabelsRequirement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("hazmatLabelsRequirement")
			}
			return err
		}
	}

	return nil
}

func (m *ComplianceAttributes) validateItemValueRequirement(formats strfmt.Registry) error {

	if err := validate.Required("itemValueRequirement", "body", m.ItemValueRequirement); err != nil {
		return err
	}

	if err := validate.Required("itemValueRequirement", "body", m.ItemValueRequirement); err != nil {
		return err
	}

	if m.ItemValueRequirement != nil {
		if err := m.ItemValueRequirement.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("itemValueRequirement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("itemValueRequirement")
			}
			return err
		}
	}

	return nil
}

func (m *ComplianceAttributes) validateSerialNumberRequirement(formats strfmt.Registry) error {

	if err := validate.Required("serialNumberRequirement", "body", m.SerialNumberRequirement); err != nil {
		return err
	}

	if err := validate.Required("serialNumberRequirement", "body", m.SerialNumberRequirement); err != nil {
		return err
	}

	if m.SerialNumberRequirement != nil {
		if err := m.SerialNumberRequirement.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("serialNumberRequirement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("serialNumberRequirement")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this compliance attributes based on the context it is used
func (m *ComplianceAttributes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCountryOfOriginRequirement(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHazmatLabelsRequirement(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateItemValueRequirement(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSerialNumberRequirement(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComplianceAttributes) contextValidateCountryOfOriginRequirement(ctx context.Context, formats strfmt.Registry) error {

	if m.CountryOfOriginRequirement != nil {
		if err := m.CountryOfOriginRequirement.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("countryOfOriginRequirement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("countryOfOriginRequirement")
			}
			return err
		}
	}

	return nil
}

func (m *ComplianceAttributes) contextValidateHazmatLabelsRequirement(ctx context.Context, formats strfmt.Registry) error {

	if m.HazmatLabelsRequirement != nil {
		if err := m.HazmatLabelsRequirement.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("hazmatLabelsRequirement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("hazmatLabelsRequirement")
			}
			return err
		}
	}

	return nil
}

func (m *ComplianceAttributes) contextValidateItemValueRequirement(ctx context.Context, formats strfmt.Registry) error {

	if m.ItemValueRequirement != nil {
		if err := m.ItemValueRequirement.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("itemValueRequirement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("itemValueRequirement")
			}
			return err
		}
	}

	return nil
}

func (m *ComplianceAttributes) contextValidateSerialNumberRequirement(ctx context.Context, formats strfmt.Registry) error {

	if m.SerialNumberRequirement != nil {
		if err := m.SerialNumberRequirement.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("serialNumberRequirement")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("serialNumberRequirement")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComplianceAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComplianceAttributes) UnmarshalBinary(b []byte) error {
	var res ComplianceAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
