// Code generated by go-swagger; DO NOT EDIT.

package external_fulfillment_shipments_2024_09_11_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PartyIdentificationInfo Party identification details for the shipment, applicable to direct fulfillment shipments.
//
// swagger:model PartyIdentificationInfo
type PartyIdentificationInfo struct {

	// Address details of the party.
	Address *Address `json:"address,omitempty"`

	// Assigned identification for the party. For example, a warehouse code or vendor code.
	// Required: true
	PartyID *string `json:"partyId"`

	// Assigned identification for the party. For example, a warehouse code or vendor code.
	// Required: true
	// Enum: [BILL_TO_PARTY SHIP_TO_PARTY SHIP_FROM_PARTY SELLING_PARTY]
	PartyType *string `json:"partyType"`

	// Tax registration details of the entity.
	TaxInfo *TaxRegistrationInfo `json:"taxInfo,omitempty"`
}

// Validate validates this party identification info
func (m *PartyIdentificationInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePartyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePartyType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaxInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PartyIdentificationInfo) validateAddress(formats strfmt.Registry) error {
	if swag.IsZero(m.Address) { // not required
		return nil
	}

	if m.Address != nil {
		if err := m.Address.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("address")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("address")
			}
			return err
		}
	}

	return nil
}

func (m *PartyIdentificationInfo) validatePartyID(formats strfmt.Registry) error {

	if err := validate.Required("partyId", "body", m.PartyID); err != nil {
		return err
	}

	return nil
}

var partyIdentificationInfoTypePartyTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["BILL_TO_PARTY","SHIP_TO_PARTY","SHIP_FROM_PARTY","SELLING_PARTY"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		partyIdentificationInfoTypePartyTypePropEnum = append(partyIdentificationInfoTypePartyTypePropEnum, v)
	}
}

const (

	// PartyIdentificationInfoPartyTypeBILLTOPARTY captures enum value "BILL_TO_PARTY"
	PartyIdentificationInfoPartyTypeBILLTOPARTY string = "BILL_TO_PARTY"

	// PartyIdentificationInfoPartyTypeSHIPTOPARTY captures enum value "SHIP_TO_PARTY"
	PartyIdentificationInfoPartyTypeSHIPTOPARTY string = "SHIP_TO_PARTY"

	// PartyIdentificationInfoPartyTypeSHIPFROMPARTY captures enum value "SHIP_FROM_PARTY"
	PartyIdentificationInfoPartyTypeSHIPFROMPARTY string = "SHIP_FROM_PARTY"

	// PartyIdentificationInfoPartyTypeSELLINGPARTY captures enum value "SELLING_PARTY"
	PartyIdentificationInfoPartyTypeSELLINGPARTY string = "SELLING_PARTY"
)

// prop value enum
func (m *PartyIdentificationInfo) validatePartyTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, partyIdentificationInfoTypePartyTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PartyIdentificationInfo) validatePartyType(formats strfmt.Registry) error {

	if err := validate.Required("partyType", "body", m.PartyType); err != nil {
		return err
	}

	// value enum
	if err := m.validatePartyTypeEnum("partyType", "body", *m.PartyType); err != nil {
		return err
	}

	return nil
}

func (m *PartyIdentificationInfo) validateTaxInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.TaxInfo) { // not required
		return nil
	}

	if m.TaxInfo != nil {
		if err := m.TaxInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("taxInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("taxInfo")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this party identification info based on the context it is used
func (m *PartyIdentificationInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAddress(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTaxInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PartyIdentificationInfo) contextValidateAddress(ctx context.Context, formats strfmt.Registry) error {

	if m.Address != nil {
		if err := m.Address.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("address")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("address")
			}
			return err
		}
	}

	return nil
}

func (m *PartyIdentificationInfo) contextValidateTaxInfo(ctx context.Context, formats strfmt.Registry) error {

	if m.TaxInfo != nil {
		if err := m.TaxInfo.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("taxInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("taxInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PartyIdentificationInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PartyIdentificationInfo) UnmarshalBinary(b []byte) error {
	var res PartyIdentificationInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
