// Code generated by go-swagger; DO NOT EDIT.

package external_fulfillment_shipments_2024_09_11_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateSandboxShipmentRequest The request object for updating a sandbox shipment. The `updates` object is required for `SHIPMENT_STATUS_CHANGE` and `TRANSPORT_CAPACITY_CHANGE` update types, and must not be provided for `INVOICE_AVAILABILITY_CHANGE`.
// Example: {"updateType":"SHIPMENT_STATUS_CHANGE","updates":{"status":"SHIPPED"}}
//
// swagger:model UpdateSandboxShipmentRequest
type UpdateSandboxShipmentRequest struct {

	// The type of update to apply to the shipment.
	// Example: SHIPMENT_STATUS_CHANGE
	// Required: true
	// Enum: [SHIPMENT_STATUS_CHANGE INVOICE_AVAILABILITY_CHANGE TRANSPORT_CAPACITY_CHANGE]
	UpdateType *string `json:"updateType"`

	// updates
	Updates *SandboxShipmentUpdates `json:"updates,omitempty"`
}

// Validate validates this update sandbox shipment request
func (m *UpdateSandboxShipmentRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUpdateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var updateSandboxShipmentRequestTypeUpdateTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SHIPMENT_STATUS_CHANGE","INVOICE_AVAILABILITY_CHANGE","TRANSPORT_CAPACITY_CHANGE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateSandboxShipmentRequestTypeUpdateTypePropEnum = append(updateSandboxShipmentRequestTypeUpdateTypePropEnum, v)
	}
}

const (

	// UpdateSandboxShipmentRequestUpdateTypeSHIPMENTSTATUSCHANGE captures enum value "SHIPMENT_STATUS_CHANGE"
	UpdateSandboxShipmentRequestUpdateTypeSHIPMENTSTATUSCHANGE string = "SHIPMENT_STATUS_CHANGE"

	// UpdateSandboxShipmentRequestUpdateTypeINVOICEAVAILABILITYCHANGE captures enum value "INVOICE_AVAILABILITY_CHANGE"
	UpdateSandboxShipmentRequestUpdateTypeINVOICEAVAILABILITYCHANGE string = "INVOICE_AVAILABILITY_CHANGE"

	// UpdateSandboxShipmentRequestUpdateTypeTRANSPORTCAPACITYCHANGE captures enum value "TRANSPORT_CAPACITY_CHANGE"
	UpdateSandboxShipmentRequestUpdateTypeTRANSPORTCAPACITYCHANGE string = "TRANSPORT_CAPACITY_CHANGE"
)

// prop value enum
func (m *UpdateSandboxShipmentRequest) validateUpdateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, updateSandboxShipmentRequestTypeUpdateTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UpdateSandboxShipmentRequest) validateUpdateType(formats strfmt.Registry) error {

	if err := validate.Required("updateType", "body", m.UpdateType); err != nil {
		return err
	}

	// value enum
	if err := m.validateUpdateTypeEnum("updateType", "body", *m.UpdateType); err != nil {
		return err
	}

	return nil
}

func (m *UpdateSandboxShipmentRequest) validateUpdates(formats strfmt.Registry) error {
	if swag.IsZero(m.Updates) { // not required
		return nil
	}

	if m.Updates != nil {
		if err := m.Updates.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updates")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updates")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this update sandbox shipment request based on the context it is used
func (m *UpdateSandboxShipmentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUpdates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateSandboxShipmentRequest) contextValidateUpdates(ctx context.Context, formats strfmt.Registry) error {

	if m.Updates != nil {
		if err := m.Updates.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updates")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updates")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateSandboxShipmentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateSandboxShipmentRequest) UnmarshalBinary(b []byte) error {
	var res UpdateSandboxShipmentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
