// Code generated by go-swagger; DO NOT EDIT.

package awd

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewConfirmInboundParams creates a new ConfirmInboundParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewConfirmInboundParams() *ConfirmInboundParams {
	return &ConfirmInboundParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewConfirmInboundParamsWithTimeout creates a new ConfirmInboundParams object
// with the ability to set a timeout on a request.
func NewConfirmInboundParamsWithTimeout(timeout time.Duration) *ConfirmInboundParams {
	return &ConfirmInboundParams{
		timeout: timeout,
	}
}

// NewConfirmInboundParamsWithContext creates a new ConfirmInboundParams object
// with the ability to set a context for a request.
func NewConfirmInboundParamsWithContext(ctx context.Context) *ConfirmInboundParams {
	return &ConfirmInboundParams{
		Context: ctx,
	}
}

// NewConfirmInboundParamsWithHTTPClient creates a new ConfirmInboundParams object
// with the ability to set a custom HTTPClient for a request.
func NewConfirmInboundParamsWithHTTPClient(client *http.Client) *ConfirmInboundParams {
	return &ConfirmInboundParams{
		HTTPClient: client,
	}
}

/*
ConfirmInboundParams contains all the parameters to send to the API endpoint

	for the confirm inbound operation.

	Typically these are written to a http.Request.
*/
type ConfirmInboundParams struct {

	/* OrderID.

	   ID for the inbound order you want to confirm.
	*/
	OrderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the confirm inbound params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConfirmInboundParams) WithDefaults() *ConfirmInboundParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the confirm inbound params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConfirmInboundParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the confirm inbound params
func (o *ConfirmInboundParams) WithTimeout(timeout time.Duration) *ConfirmInboundParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the confirm inbound params
func (o *ConfirmInboundParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the confirm inbound params
func (o *ConfirmInboundParams) WithContext(ctx context.Context) *ConfirmInboundParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the confirm inbound params
func (o *ConfirmInboundParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the confirm inbound params
func (o *ConfirmInboundParams) WithHTTPClient(client *http.Client) *ConfirmInboundParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the confirm inbound params
func (o *ConfirmInboundParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderID adds the orderID to the confirm inbound params
func (o *ConfirmInboundParams) WithOrderID(orderID string) *ConfirmInboundParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the confirm inbound params
func (o *ConfirmInboundParams) SetOrderID(orderID string) {
	o.OrderID = orderID
}

// WriteToRequest writes these params to a swagger request
func (o *ConfirmInboundParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orderId
	if err := r.SetPathParam("orderId", o.OrderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
