// Code generated by go-swagger; DO NOT EDIT.

package easy_ship_2022_03_23_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Dimension The numerical value of the specified dimension.
//
// swagger:model Dimension
type Dimension float32

// Validate validates this dimension
func (m Dimension) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Minimum("", "body", float64(m), 0.01, false); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this dimension based on context it is used
func (m Dimension) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
