// Code generated by go-swagger; DO NOT EDIT.

package sandbox_location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/renabled/amzn-sp-api-go/api/externalFulfillmentLocation_2026-07-30/external_fulfillment_location_2026_07_30_models"
)

// NewCreateSandboxLocationParams creates a new CreateSandboxLocationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSandboxLocationParams() *CreateSandboxLocationParams {
	return &CreateSandboxLocationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSandboxLocationParamsWithTimeout creates a new CreateSandboxLocationParams object
// with the ability to set a timeout on a request.
func NewCreateSandboxLocationParamsWithTimeout(timeout time.Duration) *CreateSandboxLocationParams {
	return &CreateSandboxLocationParams{
		timeout: timeout,
	}
}

// NewCreateSandboxLocationParamsWithContext creates a new CreateSandboxLocationParams object
// with the ability to set a context for a request.
func NewCreateSandboxLocationParamsWithContext(ctx context.Context) *CreateSandboxLocationParams {
	return &CreateSandboxLocationParams{
		Context: ctx,
	}
}

// NewCreateSandboxLocationParamsWithHTTPClient creates a new CreateSandboxLocationParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSandboxLocationParamsWithHTTPClient(client *http.Client) *CreateSandboxLocationParams {
	return &CreateSandboxLocationParams{
		HTTPClient: client,
	}
}

/*
CreateSandboxLocationParams contains all the parameters to send to the API endpoint

	for the create sandbox location operation.

	Typically these are written to a http.Request.
*/
type CreateSandboxLocationParams struct {

	/* Body.

	   The request body for creating a sandbox location.
	*/
	Body *external_fulfillment_location_2026_07_30_models.CreateSandboxLocationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create sandbox location params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSandboxLocationParams) WithDefaults() *CreateSandboxLocationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create sandbox location params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSandboxLocationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create sandbox location params
func (o *CreateSandboxLocationParams) WithTimeout(timeout time.Duration) *CreateSandboxLocationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create sandbox location params
func (o *CreateSandboxLocationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create sandbox location params
func (o *CreateSandboxLocationParams) WithContext(ctx context.Context) *CreateSandboxLocationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create sandbox location params
func (o *CreateSandboxLocationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create sandbox location params
func (o *CreateSandboxLocationParams) WithHTTPClient(client *http.Client) *CreateSandboxLocationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create sandbox location params
func (o *CreateSandboxLocationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create sandbox location params
func (o *CreateSandboxLocationParams) WithBody(body *external_fulfillment_location_2026_07_30_models.CreateSandboxLocationRequest) *CreateSandboxLocationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create sandbox location params
func (o *CreateSandboxLocationParams) SetBody(body *external_fulfillment_location_2026_07_30_models.CreateSandboxLocationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSandboxLocationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
