// Code generated by go-swagger; DO NOT EDIT.

package catalog_items_2022_04_01_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ItemAsin Amazon Standard Identification Number (ASIN) is the unique identifier for an item in the Amazon catalog.
//
// swagger:model ItemAsin
type ItemAsin string

// Validate validates this item asin
func (m ItemAsin) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this item asin based on context it is used
func (m ItemAsin) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
