// Code generated by go-swagger; DO NOT EDIT.

package notifications_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AggregationFilter Use this filter to select the aggregation time period at which to send notifications (e.g. limit to one notification every five minutes for high frequency notifications).
//
// swagger:model AggregationFilter
type AggregationFilter struct {

	// aggregation settings
	AggregationSettings *AggregationSettings `json:"aggregationSettings,omitempty"`
}

// Validate validates this aggregation filter
func (m *AggregationFilter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAggregationSettings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AggregationFilter) validateAggregationSettings(formats strfmt.Registry) error {
	if swag.IsZero(m.AggregationSettings) { // not required
		return nil
	}

	if m.AggregationSettings != nil {
		if err := m.AggregationSettings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("aggregationSettings")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("aggregationSettings")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this aggregation filter based on the context it is used
func (m *AggregationFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAggregationSettings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AggregationFilter) contextValidateAggregationSettings(ctx context.Context, formats strfmt.Registry) error {

	if m.AggregationSettings != nil {
		if err := m.AggregationSettings.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("aggregationSettings")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("aggregationSettings")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AggregationFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AggregationFilter) UnmarshalBinary(b []byte) error {
	var res AggregationFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
