// Code generated by go-swagger; DO NOT EDIT.

package fulfillment_outbound_2026_07_04_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderOrigin The origin of the fulfillment.
// Example: {"countryCode":"US"}
//
// swagger:model OrderOrigin
type OrderOrigin struct {

	// The two-digit country code (in ISO 3166-1 alpha-2 format) for the country where the items ship from.
	// Required: true
	CountryCode *CountryCode `json:"countryCode"`
}

// Validate validates this order origin
func (m *OrderOrigin) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCountryCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderOrigin) validateCountryCode(formats strfmt.Registry) error {

	if err := validate.Required("countryCode", "body", m.CountryCode); err != nil {
		return err
	}

	if err := validate.Required("countryCode", "body", m.CountryCode); err != nil {
		return err
	}

	if m.CountryCode != nil {
		if err := m.CountryCode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("countryCode")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("countryCode")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this order origin based on the context it is used
func (m *OrderOrigin) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCountryCode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderOrigin) contextValidateCountryCode(ctx context.Context, formats strfmt.Registry) error {

	if m.CountryCode != nil {
		if err := m.CountryCode.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("countryCode")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("countryCode")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderOrigin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderOrigin) UnmarshalBinary(b []byte) error {
	var res OrderOrigin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
