// Code generated by go-swagger; DO NOT EDIT.

package fulfillment_outbound_2026_07_04_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ShipmentItem Item information for a shipment in a fulfillment order.
// Example: {"amount":{"unit":"EACHES","value":"1.0"},"lineItemId":"lineItem1","packageId":"PKG-abc123def456","productIdentifier":{"amazonSku":"product123"},"shipmentItemId":"SI001","unitIdentifiers":{"ASIN":["B01234567","B07654321"],"SKU":["ABC123","XYZ789"],"UPC":["012345678901","987654321098"]}}
//
// swagger:model ShipmentItem
type ShipmentItem struct {

	// amount
	// Required: true
	Amount *Amount `json:"amount"`

	// The fulfillment order item identifier that the seller created and submitted with a call to the `createOrder` operation.
	// Required: true
	LineItemID *string `json:"lineItemId"`

	// An identifier for the package that contains the item quantity.
	// Max Length: 40
	PackageID string `json:"packageId,omitempty"`

	// product identifier
	// Required: true
	ProductIdentifier *ProductIdentifier `json:"productIdentifier"`

	// A unique identifier for the shipment item.
	ShipmentItemID string `json:"shipmentItemId,omitempty"`

	// The manufacturer lot codes of the shipped items.
	UnitIdentifiers UnitIdentifiers `json:"unitIdentifiers,omitempty"`
}

// Validate validates this shipment item
func (m *ShipmentItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLineItemID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePackageID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProductIdentifier(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnitIdentifiers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShipmentItem) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	if m.Amount != nil {
		if err := m.Amount.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amount")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("amount")
			}
			return err
		}
	}

	return nil
}

func (m *ShipmentItem) validateLineItemID(formats strfmt.Registry) error {

	if err := validate.Required("lineItemId", "body", m.LineItemID); err != nil {
		return err
	}

	return nil
}

func (m *ShipmentItem) validatePackageID(formats strfmt.Registry) error {
	if swag.IsZero(m.PackageID) { // not required
		return nil
	}

	if err := validate.MaxLength("packageId", "body", m.PackageID, 40); err != nil {
		return err
	}

	return nil
}

func (m *ShipmentItem) validateProductIdentifier(formats strfmt.Registry) error {

	if err := validate.Required("productIdentifier", "body", m.ProductIdentifier); err != nil {
		return err
	}

	if m.ProductIdentifier != nil {
		if err := m.ProductIdentifier.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("productIdentifier")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("productIdentifier")
			}
			return err
		}
	}

	return nil
}

func (m *ShipmentItem) validateUnitIdentifiers(formats strfmt.Registry) error {
	if swag.IsZero(m.UnitIdentifiers) { // not required
		return nil
	}

	if m.UnitIdentifiers != nil {
		if err := m.UnitIdentifiers.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("unitIdentifiers")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("unitIdentifiers")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this shipment item based on the context it is used
func (m *ShipmentItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProductIdentifier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUnitIdentifiers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShipmentItem) contextValidateAmount(ctx context.Context, formats strfmt.Registry) error {

	if m.Amount != nil {
		if err := m.Amount.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amount")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("amount")
			}
			return err
		}
	}

	return nil
}

func (m *ShipmentItem) contextValidateProductIdentifier(ctx context.Context, formats strfmt.Registry) error {

	if m.ProductIdentifier != nil {
		if err := m.ProductIdentifier.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("productIdentifier")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("productIdentifier")
			}
			return err
		}
	}

	return nil
}

func (m *ShipmentItem) contextValidateUnitIdentifiers(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UnitIdentifiers.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("unitIdentifiers")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("unitIdentifiers")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ShipmentItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShipmentItem) UnmarshalBinary(b []byte) error {
	var res ShipmentItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
