// Code generated by go-swagger; DO NOT EDIT.

package fba_inbound

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEstimateTransportParams creates a new EstimateTransportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEstimateTransportParams() *EstimateTransportParams {
	return &EstimateTransportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEstimateTransportParamsWithTimeout creates a new EstimateTransportParams object
// with the ability to set a timeout on a request.
func NewEstimateTransportParamsWithTimeout(timeout time.Duration) *EstimateTransportParams {
	return &EstimateTransportParams{
		timeout: timeout,
	}
}

// NewEstimateTransportParamsWithContext creates a new EstimateTransportParams object
// with the ability to set a context for a request.
func NewEstimateTransportParamsWithContext(ctx context.Context) *EstimateTransportParams {
	return &EstimateTransportParams{
		Context: ctx,
	}
}

// NewEstimateTransportParamsWithHTTPClient creates a new EstimateTransportParams object
// with the ability to set a custom HTTPClient for a request.
func NewEstimateTransportParamsWithHTTPClient(client *http.Client) *EstimateTransportParams {
	return &EstimateTransportParams{
		HTTPClient: client,
	}
}

/*
EstimateTransportParams contains all the parameters to send to the API endpoint

	for the estimate transport operation.

	Typically these are written to a http.Request.
*/
type EstimateTransportParams struct {

	/* ShipmentID.

	   A shipment identifier originally returned by the createInboundShipmentPlan operation.
	*/
	ShipmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the estimate transport params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EstimateTransportParams) WithDefaults() *EstimateTransportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the estimate transport params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EstimateTransportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the estimate transport params
func (o *EstimateTransportParams) WithTimeout(timeout time.Duration) *EstimateTransportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the estimate transport params
func (o *EstimateTransportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the estimate transport params
func (o *EstimateTransportParams) WithContext(ctx context.Context) *EstimateTransportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the estimate transport params
func (o *EstimateTransportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the estimate transport params
func (o *EstimateTransportParams) WithHTTPClient(client *http.Client) *EstimateTransportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the estimate transport params
func (o *EstimateTransportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithShipmentID adds the shipmentID to the estimate transport params
func (o *EstimateTransportParams) WithShipmentID(shipmentID string) *EstimateTransportParams {
	o.SetShipmentID(shipmentID)
	return o
}

// SetShipmentID adds the shipmentId to the estimate transport params
func (o *EstimateTransportParams) SetShipmentID(shipmentID string) {
	o.ShipmentID = shipmentID
}

// WriteToRequest writes these params to a swagger request
func (o *EstimateTransportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param shipmentId
	if err := r.SetPathParam("shipmentId", o.ShipmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
