// Code generated by go-swagger; DO NOT EDIT.

package seller_wallet_2024_03_01_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransferScheduleRequest Request body to initiate a scheduled transfer from a SW bank account to another customer defined bank account
//
// Example: {"destinationAccountId":"amzn1.account.AJKBFWEJFBNH2KCJPII5FBN","destinationTransactionInstrument":{"accountHolderName":"John Doe","bankAccount":{"accountCountryCode":"CN","accountCurrency":"CNY","bankAccountNumberFormat":"BBAN","bankAccountNumberTail":"819","bankAccountOwnershipType":"SELF","bankNumberFormat":"BASIC","routingNumber":"HBUKGB4B"},"bankAccountNumber":"GB29RBOS60161331926819"},"paymentPreference":{"paymentPreferencePaymentType":"PERCENTAGE","value":25.5},"sourceAccountId":"amzn1.account.SMUGN2EN3ZHWSRJKH2KCJPII5JEI","sourceCurrencyCode":"USD","transactionType":"DEBIT","transferScheduleInformation":{"scheduleEndDate":"2027-03-01T00:00:00Z","scheduleExpression":{"recurringFrequency":"WEEKLY","scheduleExpressionType":"RECURRING"},"scheduleStartDate":"2024-03-01T00:00:00Z","scheduleType":"TIME_BASED"},"transferScheduleStatus":"ENABLED"}
//
// swagger:model TransferScheduleRequest
type TransferScheduleRequest struct {

	// Optional field to specify the unique identifier of the destination bank account where the money needs to be deposited
	//
	// Example: amzn1.account.AJKBFWEJFBNH2KCJPII5FBN
	// Required: true
	DestinationAccountID *string `json:"destinationAccountId"`

	// Destination bank account details of the transaction request
	//
	// Required: true
	DestinationTransactionInstrument *TransactionInstrumentDetails `json:"destinationTransactionInstrument"`

	// Payment preference of the scheduled transfer
	//
	// Required: true
	PaymentPreference *PaymentPreference `json:"paymentPreference"`

	// The unique identifier of the source Amazon SW bank account from where the money needs to be debited
	//
	// Example: amzn1.account.SMUGN2EN3ZHWSRJKH2KCJPII5JEI
	// Required: true
	SourceAccountID *string `json:"sourceAccountId"`

	// Represents 3 letter currency code in ISO 4217 standard format of the source payment method country
	//
	// Example: GBP
	// Required: true
	SourceCurrencyCode *string `json:"sourceCurrencyCode"`

	// Type of the scheduled transaction
	//
	// Required: true
	TransactionType *TransactionType `json:"transactionType"`

	// Fields required for the scheduled transfer
	//
	// Required: true
	TransferScheduleInformation *TransferScheduleInformation `json:"transferScheduleInformation"`

	// Type of the transaction schedule which is mandatory field in request body if a transfer schedule needs to be updated
	//
	TransferScheduleStatus TransferScheduleStatus `json:"transferScheduleStatus,omitempty"`
}

// Validate validates this transfer schedule request
func (m *TransferScheduleRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDestinationAccountID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDestinationTransactionInstrument(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePaymentPreference(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSourceAccountID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSourceCurrencyCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransferScheduleInformation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransferScheduleStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransferScheduleRequest) validateDestinationAccountID(formats strfmt.Registry) error {

	if err := validate.Required("destinationAccountId", "body", m.DestinationAccountID); err != nil {
		return err
	}

	return nil
}

func (m *TransferScheduleRequest) validateDestinationTransactionInstrument(formats strfmt.Registry) error {

	if err := validate.Required("destinationTransactionInstrument", "body", m.DestinationTransactionInstrument); err != nil {
		return err
	}

	if m.DestinationTransactionInstrument != nil {
		if err := m.DestinationTransactionInstrument.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("destinationTransactionInstrument")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("destinationTransactionInstrument")
			}
			return err
		}
	}

	return nil
}

func (m *TransferScheduleRequest) validatePaymentPreference(formats strfmt.Registry) error {

	if err := validate.Required("paymentPreference", "body", m.PaymentPreference); err != nil {
		return err
	}

	if m.PaymentPreference != nil {
		if err := m.PaymentPreference.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("paymentPreference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("paymentPreference")
			}
			return err
		}
	}

	return nil
}

func (m *TransferScheduleRequest) validateSourceAccountID(formats strfmt.Registry) error {

	if err := validate.Required("sourceAccountId", "body", m.SourceAccountID); err != nil {
		return err
	}

	return nil
}

func (m *TransferScheduleRequest) validateSourceCurrencyCode(formats strfmt.Registry) error {

	if err := validate.Required("sourceCurrencyCode", "body", m.SourceCurrencyCode); err != nil {
		return err
	}

	return nil
}

func (m *TransferScheduleRequest) validateTransactionType(formats strfmt.Registry) error {

	if err := validate.Required("transactionType", "body", m.TransactionType); err != nil {
		return err
	}

	if err := validate.Required("transactionType", "body", m.TransactionType); err != nil {
		return err
	}

	if m.TransactionType != nil {
		if err := m.TransactionType.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("transactionType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("transactionType")
			}
			return err
		}
	}

	return nil
}

func (m *TransferScheduleRequest) validateTransferScheduleInformation(formats strfmt.Registry) error {

	if err := validate.Required("transferScheduleInformation", "body", m.TransferScheduleInformation); err != nil {
		return err
	}

	if m.TransferScheduleInformation != nil {
		if err := m.TransferScheduleInformation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("transferScheduleInformation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("transferScheduleInformation")
			}
			return err
		}
	}

	return nil
}

func (m *TransferScheduleRequest) validateTransferScheduleStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.TransferScheduleStatus) { // not required
		return nil
	}

	if err := m.TransferScheduleStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("transferScheduleStatus")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("transferScheduleStatus")
		}
		return err
	}

	return nil
}

// ContextValidate validate this transfer schedule request based on the context it is used
func (m *TransferScheduleRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDestinationTransactionInstrument(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePaymentPreference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransactionType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransferScheduleInformation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransferScheduleStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransferScheduleRequest) contextValidateDestinationTransactionInstrument(ctx context.Context, formats strfmt.Registry) error {

	if m.DestinationTransactionInstrument != nil {
		if err := m.DestinationTransactionInstrument.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("destinationTransactionInstrument")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("destinationTransactionInstrument")
			}
			return err
		}
	}

	return nil
}

func (m *TransferScheduleRequest) contextValidatePaymentPreference(ctx context.Context, formats strfmt.Registry) error {

	if m.PaymentPreference != nil {
		if err := m.PaymentPreference.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("paymentPreference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("paymentPreference")
			}
			return err
		}
	}

	return nil
}

func (m *TransferScheduleRequest) contextValidateTransactionType(ctx context.Context, formats strfmt.Registry) error {

	if m.TransactionType != nil {
		if err := m.TransactionType.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("transactionType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("transactionType")
			}
			return err
		}
	}

	return nil
}

func (m *TransferScheduleRequest) contextValidateTransferScheduleInformation(ctx context.Context, formats strfmt.Registry) error {

	if m.TransferScheduleInformation != nil {
		if err := m.TransferScheduleInformation.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("transferScheduleInformation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("transferScheduleInformation")
			}
			return err
		}
	}

	return nil
}

func (m *TransferScheduleRequest) contextValidateTransferScheduleStatus(ctx context.Context, formats strfmt.Registry) error {

	if err := m.TransferScheduleStatus.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("transferScheduleStatus")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("transferScheduleStatus")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TransferScheduleRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransferScheduleRequest) UnmarshalBinary(b []byte) error {
	var res TransferScheduleRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
