// Code generated by go-swagger; DO NOT EDIT.

package product_pricing_2022_05_01_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SegmentDetails The details about the segment.
//
// swagger:model SegmentDetails
type SegmentDetails struct {

	// Glance view weight percentage for this segment. The glance views for this segment as a percentage of total glance views across all segments on the ASIN. A higher percentage indicates more Amazon customers see this offer as the Featured Offer.
	GlanceViewWeightPercentage float64 `json:"glanceViewWeightPercentage,omitempty"`
}

// Validate validates this segment details
func (m *SegmentDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this segment details based on context it is used
func (m *SegmentDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SegmentDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SegmentDetails) UnmarshalBinary(b []byte) error {
	var res SegmentDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
