// Code generated by go-swagger; DO NOT EDIT.

package awd_2024_05_09_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReplenishmentOrderCreationData This structure represents the payload for creating an AFN Replenishment Order.
// By default, all replenishment orders created support Partial order preferences.
// Example: {"preferences":{"confirmation":"AUTO"},"products":[{"quantity":1,"sku":"testPen"}]}
//
// swagger:model ReplenishmentOrderCreationData
type ReplenishmentOrderCreationData struct {

	// preferences
	Preferences *ReplenishmentPreferences `json:"preferences,omitempty"`

	// Requested amount of single product units to be replenished.
	// Example: [{"quantity":1,"sku":"TestSKU"}]
	Products []*DistributionProduct `json:"products"`
}

// Validate validates this replenishment order creation data
func (m *ReplenishmentOrderCreationData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePreferences(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProducts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReplenishmentOrderCreationData) validatePreferences(formats strfmt.Registry) error {
	if swag.IsZero(m.Preferences) { // not required
		return nil
	}

	if m.Preferences != nil {
		if err := m.Preferences.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("preferences")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("preferences")
			}
			return err
		}
	}

	return nil
}

func (m *ReplenishmentOrderCreationData) validateProducts(formats strfmt.Registry) error {
	if swag.IsZero(m.Products) { // not required
		return nil
	}

	for i := 0; i < len(m.Products); i++ {
		if swag.IsZero(m.Products[i]) { // not required
			continue
		}

		if m.Products[i] != nil {
			if err := m.Products[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("products" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("products" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this replenishment order creation data based on the context it is used
func (m *ReplenishmentOrderCreationData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePreferences(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProducts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReplenishmentOrderCreationData) contextValidatePreferences(ctx context.Context, formats strfmt.Registry) error {

	if m.Preferences != nil {
		if err := m.Preferences.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("preferences")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("preferences")
			}
			return err
		}
	}

	return nil
}

func (m *ReplenishmentOrderCreationData) contextValidateProducts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Products); i++ {

		if m.Products[i] != nil {
			if err := m.Products[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("products" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("products" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReplenishmentOrderCreationData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReplenishmentOrderCreationData) UnmarshalBinary(b []byte) error {
	var res ReplenishmentOrderCreationData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
